version: "3.9"
services:
  db:
    image: postgres:12-alpine
    container_name: postgres_db_ide
    ports:
      - 5432:5432
    restart: always
    env_file: ./postgres-db/.env
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: extras/Dockerfile.nginx
    container_name: nginx_ide
    ports:
      - 80:80
    volumes:
      - ./extras/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
    restart: always
    networks:
      - backend-network


  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-be
    ports:
      - "8000:8000"
    depends_on:
    - db
    restart: always
    networks:
      - backend-network
    volumes:
      - ./auth/:/home/
    env_file: ./auth/.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_ide
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - backend-network
  
  redis:
    image: redis:latest
    container_name: redis_ide_container
    ports:
      - 6379:6379
    restart: always
    networks:
      - backend-network
    volumes:
      - redis-data:/data



networks:
  backend-network:


volumes:
  pgdata:
  redis-data:

