"""Added initial table

Revision ID: 50177c80efa3
Revises: 930c4c400580
Create Date: 2023-11-28 20:23:48.999960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50177c80efa3'
down_revision = '930c4c400580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=225), nullable=False),
    sa.Column('content', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code_title', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('code_language', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code_output', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code_input', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='codes_pkey')
    )
    op.drop_table('mails')
    # ### end Alembic commands ###
